- name: Launch cloudctl commands
  hosts: localhost
  gather_facts: no

  vars:
    var_mcm_endpoint: ""
    var_mcm_user: ""
    var_mcm_password: ""
    var_mcm_namespace: ""
    var_helm_package: ""
    var_helm_appname: ""

  tasks:
    - name: Execute clouctl login
      shell: "cloudctl login -a {{ var_mcm_endpoint }} --skip-ssl-validation -u {{ var_mcm_user }} -p {{ var_mcm_password }} -n {{ var_mcm_namespace }}; helm init --client-only; helm version --tls"
      args:
        chdir: "/root/"
