- name: Launch cloudctl commands
  hosts: all
  gather_facts: no

  vars:
    var_mcm_endpoint: ""
    var_mcm_user: ""
    var_mcm_password: ""
    var_mcm_namespace: ""
    var_helm_package: ""
    var_helm_appname: ""
    var_helm_appversion: ""
    var_helm_deploymentname: ""

  tasks:
    - name: Execute clouctl
      shell: "cloudctl login -a {{ var_mcm_endpoint }} --skip-ssl-validation -u {{ var_mcm_user }} -p {{ var_mcm_password }} -n {{ var_mcm_namespace }}; helm init --client-only; helm version --tls; helm delete {{ var_helm_appname }} --tls --purge; helm install {{ var_helm_package }} --name {{ var_helm_appname }}  --namespace {{ var_mcm_namespace }} --set version={{ var_helm_appversion }} --tls; sleep 5; cloudctl mc get deployment {{ var_helm_deploymentname }}  -o yaml --all-clusters -n {{ var_mcm_namespace }} | grep {{ var_helm_appversion }}"
      args:
        chdir: "/root/"
      ignore_errors: yes
