---
- name: Test osp roles
  hosts: localhost
  gather_facts: no

  tasks:

  - block:
      - name: gather facts
        include_role:
          name: osp/osp-facts
          tasks_from: get-osp-facts
    when: role_osp_facts == 'true'

  - block:
      - name: create flavor
        include_role:
          name: osp/osp-flavor
          tasks_from: create-osp-flavor
    when: role_osp_flavor == 'true'

  - block:
      - name: create instance
        include_role:
          name: osp/osp-instance
          tasks_from: create-osp-instance
    when: role_osp_instance == 'true'

  - block:
      - name: create keypair
        include_role:
          name: osp/osp-keypair
          tasks_from: generate-keypair
    when: role_osp_keypair == 'true'
