---
- name: Launch osp roles
  hosts: localhost
  gather_facts: no

  vars:
    role_osp_facts: 'false'
    role_osp_flavor: 'false'
    role_osp_keypair: 'false'
    role_osp_secugroup: 'false'
    role_osp_network: 'false'
    role_osp_instance: 'false'

  tasks:

  - block:
      - name: gather facts
        include_role:
          name: osp/osp-facts
          tasks_from: get-osp-facts
    when: role_osp_facts == 'true'

  - block:
      - name: create flavor
        include_role:
          name: osp/osp-flavor
          tasks_from: create-osp-flavor
    when: role_osp_flavor == 'true'

  - block:
      - name: create keypair
        include_role:
          name: osp/osp-keypair
          tasks_from: generate-keypair
    when: role_osp_keypair == 'true'

  - block:
      - name: create secugroup
        include_role:
          name: osp/osp-secugroup
          tasks_from: create-secugroup-and-rules
    when: role_osp_secugroup == 'true'

  - block:
      - name: create project network
        include_role:
          name: osp/osp-network
    when: role_osp_network == 'true'

  - block:
      - name: create instance
        include_role:
          name: osp/osp-instance
          tasks_from: create-osp-instance
    when: role_osp_instance == 'true'
