---
- name: Test os roles
  hosts: localhost
  gather_facts: no

  tasks:

  - block:
      - name: gather facts
        include_role:
          name: osp/osp-facts
          tasks_from: get-osp-facts
    when: role_osp_facts == 'true'
