---

mssql_repo_src: "https://packages.microsoft.com/rhel/7/mssql-server-2019/"
mssql_repo: "mssql-server-2019"
mssql_tool_repo_src: "https://packages.microsoft.com/rhel/7/prod/"
mssql_tool_repo: "prod"
gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
mssql_package: "mssql-server"
mssql_service: "mssql-server"
mssql_tool_packages:
  - mssql-tools
  - unixODBC-devel
mssql_sa_password: 'Redhat_123'
mssql_pid: 'evaluation'
mssql_install_agent: 'y'
mssql_ports: "1433/tcp"
path_home: "/root/sql"
#path_home: "/home/cloud-user"
src_loaddb_sql: "https://raw.githubusercontent.com/davidszegedi/SQL-Server---RHEL-BM-Demo/master/Load_DB.sql"
tgt_loaddb_sql: "{{ path_home }}/Load_DB.sql"
src_querydb_sql: "https://raw.githubusercontent.com/davidszegedi/SQL-Server---RHEL-BM-Demo/master/Query_DB.sql"
tgt_querydb_sql: "{{ path_home }}/Query_DB.sql"
src_dropdb_sql: "https://raw.githubusercontent.com/davidszegedi/SQL-Server---RHEL-BM-Demo/master/Drop_DB.sql"
tgt_dropdb_sql: "{{ path_home }}/Drop_DB.sql"

var_sat: disabled
var_activationkey: ""
var_org_id: ""
