---
osp_project_name: "admin"

network_object_type: "all"

network_state: "present"
network_name: "priv_net_1"
network_external: "no"
network_shared: "no"
network_provider_network_type: "vxlan"
network_provider_segmentation_id: "50"
network_dns_domain: "8.8.8.8"

subnet_name: "priv_net_subnet_1"
subnet_state: "present"
subnet_cidr: "192.168.20.0/24"
#subnet_dns_nameserver1: "0.0.0.0"
#subnet_dns_nameserver2: "0.0.0.0"

#host_routes_destination1: "0.0.0.0/0"
#host_routes_nexthop1: "0.0.0.0"
#host_routes_destination2: "0.0.0.0/0"
#host_routes_nexthop2: "0.0.0.0"

router_state: "present"
router_name: "project_internal_router"

ext_net: "public_flat"
int_net: "priv_net_1"

ext_sub: "public_flat_subnet"
int_sub: "priv_net_subnet_1"
