---
- vsphere_guest:
    #vcenter_hostname: vcenter.mydomain.local
    #username: myuser
    #password: mypass
    validate_certs: no
    guest: "{{ var_vmname }}"
    state: "{{ var_state }}"
    vm_extra_config:
      vcpu.hotadd: yes
      mem.hotadd:  yes
      #notes: This is a test VM
      #folder: "{{ var_vm_folder }}"
    vm_disk:
      disk1:
        size_gb: "{{ var_disk_size_gb }}"
        type: "{{ var_disk_type }}"
        datastore: "{{ var_disk_datastore }}"
        # VMs can be put into folders. The value given here is either the full path
        # to the folder (e.g. production/customerA/lamp) or just the last component
        # of the path (e.g. lamp):
        folder: "{{ var_vm_folder }}"
    vm_nic:
      nic1:
        type: "{{ var_nic1_type }}"
        network: "{{ var_nic1_network }}"
        network_type: "{{ var_nic1_network_type }}"
    vm_hardware:
      memory_mb: "{{ var_vm_hw_memory_mb }}"
      num_cpus: "{{ var_vm_hw_num_cpus }}"
      osid: "{{ var_vm_hw_osid }}"
      #scsi: "{{ var_vm_hw_scsi }}"
    esxi:
      datacenter: "{{ var_datacenter }}"
      hostname: "{{ var_esx_hostname }}"
