---
- name: Create/check security group for instances
  ec2_group:
    name: "{{ ec2_security_group }}"
    description: "{{ ec2_security_group }}"
    region: "{{ ec2_region }}"
    vpc_id: "{{ ec2_vpc_id }}"
    rules:
      - proto: "tcp"
        ports:
          - 22
          - 80
          - 443
          - 389
          - 5986
        cidr_ip: "0.0.0.0/0"
    rules_egress:
      - proto: "all"
        cidr_ip: "0.0.0.0/0"
  when: ec2_group_task == True
  register: secgrp
