---
- name: Create EC2 RHEL Instance
  ec2:
    region: "{{ aws_region }}"
    group_id: "{{ secgrp.group_id }}"
    key_name: "{{ ec2_keypair }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_ami_id }}"
    vpc_subnet_id: "{{ ec2_subnet_id }}"
    assign_public_ip: yes
    state: "{{ ec2_instance_state }}"
    wait: True
    wait_timeout: 600
    instance_tags:
       Name: "{{ instance_name }}"
    count: "{{ ec2_instance_count }}"
  when: os_type == "rhel"
  register: output_ec2_RHEL

- name: wait for instances to be up and running
  wait_for_connection:
    delay: 120
